### PR TITLE
MALI: Updated Albany yaml file

### PR DESCRIPTION
**Pull request by mperego**
Updated Albany yaml file used in E3SM-MALI builds.
The file was updated by removing the options related to the old Epetra solver stack.

### CODE REVIEW

**Comment by trhille** [comment]
@mperego, I'll run the `full_integration` suite on this, but how should we test this beyond that? Can you post the results of any testing you've done?

**Comment by mperego** [comment]
Well, we don't have tests set up for E3SM-MALI yet, so I guess it's enough that the integration suite pass. We are really just removing some unused options from the yaml input file.

**Comment by trhille** [comment]
All `full_integration` tests passed validation and baseline comparison.

**Comment by mperego** [comment]
Great, so can we merge this?

**Review by trhille — APPROVED** [review]
Approved based on COMPASS testing.

**Comment by mperego** [comment]
Thanks @trhille !

**Pull request merged**
