### PR TITLE
Minor fixes related to effective pressure and mu fields

### PR DESCRIPTION
**Pull request by mperego**
Added muFriction to the restart stream of the Registry.

Removed code in the velocity interface setting the effective pressure to zero on floating ice.

### CODE REVIEW

**Comment by matthewhoffman** [comment]
@mperego , is this the change that @trhille tested last week?  If so, @trhille , can you add a comment on your test results?

**Comment by trhille** [comment]
@matthewhoffman, do you want me to add test results in this case?

**Comment by matthewhoffman** [comment]
@trhille , just comment here for the record what you tested.  Nothing overly detailed is needed.

**Comment by trhille** [comment]
I tested this by building on Cori on MPAS-Devl/landice/develop commit f0a87e3 and /global/homes/m/mperego/albany/albany-build/install-sfad24-2021-06-03/export_albany.in and compared with a run using the same MPAS hash and /global/homes/m/mperego/albany/albany-build/install-sfad24-2021-03-10/export_albany.in. I ran 2.25 years on Humboldt_1to10km_r02_20210304.nc mesh with muFriction recalculated using q=1/10, MIROC5 smb forcing, no calving or submarine melt, config_thermal_solver = 'temperature', and 10-day timesteps. 
Absolute differences in surfaceSpeed:
image

**Comment by matthewhoffman** [comment]
@mperego , do we need to worry about breaking any existing functionality or model runs by eliminating the zeroing of effective pressure in the Interface?  Also, do these changes require a corresponding Albany change?  I'm guessing no, but I'm not sure.

**Comment by mperego** [comment]
> @mperego , do we need to worry about breaking any existing functionality or model runs by eliminating the zeroing of effective pressure in the Interface? Also, do these changes require a corresponding Albany change? I'm guessing no, but I'm not sure.

Did we ever use a power law condition with MPAS passing an effective_pressure field to Albany? I can only think of the Humboldt case. But even with Humboldt we used the Hydrostatic pressure computed by Albany. So I don't think this will change anything we did so far. And for the future, we can zero the effective pressure on floating ice in Albany.

The change is needed for the newer modifications in Albany, where we prescribe a linear sliding law as a power law with `q=1`, `mu=beta` and `N=1`. If `N` is zeroed out on floating ice then we get a slightly different solution.

**Comment by mperego** [comment]
> I tested this by building on Cori on MPAS-Devl/landice/develop commit [f0a87e3](https://github.com/MALI-Dev/E3SM/commit/f0a87e36c6ccbb468bcd20b4307c5cd0713ca711) and /global/homes/m/mperego/albany/albany-build/install-sfad24-2021-06-03/export_albany.in and compared with a run using the same MPAS hash and /global/homes/m/mperego/albany/albany-build/install-sfad24-2021-03-10/export_albany.in. I ran 2.25 years on Humboldt_1to10km_r02_20210304.nc mesh with muFriction recalculated using q=1/10, MIROC5 smb forcing, no calving or submarine melt, config_thermal_solver = 'temperature', and 10-day timesteps.
> Absolute differences in surfaceSpeed (maximum value is 5.4e-16 m/s):
> image

I think this can be a bit misleading for this PR. Trevor tested against a version of Albany different than the one currently linked (otherwise the ho tests would fail) and using a version of MPAS that is not the one in this PR. A similar result would be more meaningful when we link the recent Albany master and modify the ho tests to comply with Albany changes.

**Comment by trhille** [comment]
@mperego , I'm happy to test anything else you need for this.

**Comment by mperego** [comment]
> @mperego , I'm happy to test anything else you need for this.

Thanks, but I don't think there is not much to be tested for this PR. All I'm saying is that the test you did is not particularly relevant for this specific PR.

**Comment by matthewhoffman** [comment]
@mperego , following up on your comment above, what is the current method for zeroing N in Albany if we need to do that?

I think you are right that we don't have tests in the test suite or ongoing simulations where we use N from MALI.  We had done a lot of different tests that used that a number of months back (both with Humboldt and Thwaites), but in the end, we never moved forward with any of those as production runs.

**Comment by mperego** [comment]
> @mperego , following up on your comment above, what is the current method for zeroing N in Albany if we need to do that?

```
    LandIce BCs:
      BC 0:
        Basal Friction Coefficient:
          Zero Effective Pressure On Floating Ice At Nodes: true
```

This option is available only after commit
https://github.com/SNLComputation/Albany/commit/35b8b48d43f6f554e08333a7457b135360c34d4f

**Pull request merged**
