### PR TITLE
Limit velocity to user defined maximum

### PR DESCRIPTION
**Pull request by trhille**
Limit velocity to user defined maximum instead of removing ice with unrealistic velocity. Removing unrealistically fast ice often has a cascading effect on surrounding ice, which can cause spurious catastrophic retreat.

### CODE REVIEW

**Comment by trhille** [comment]
I tested this on the 4km ISMIP6 expAE02 runs that has been giving me grief, and it successfully limited the surface velocity to `config_unrealistic_velocity` of 200 km/yr:
image
However, for some reason the basal velocity remains very high:
image

**Comment by trhille** [comment]
Comparing with another run on MALI-Dev/develop using `config_unrealistic_velocity` of 1.0 m/s also shows `basalSpeedMax`>`surfaceSpeedMax`:
image

**Comment by trhille** [comment]
https://github.com/MALI-Dev/E3SM/pull/61/commits/4856b031d420963d3929b3fbb036c151def86a22 successfully limits the basalSpeed to `config_unrealistic_velocity`:
image

**Comment by matthewhoffman** [comment]
@trhille , I pushed changes to modify how normalVelocity is modified to be consistent with how normalVelocity is defined relative to cell center velocities.  However, I'm not totally convinced the extra complexity is worth it for an operation that is pretty arbitrary to begin with.  Simply capping the normalVelocity to the same value as the cell center velocity could be a simpler alternative (though not internally consistent).

**Comment by matthewhoffman** [comment]
@trhille , I sort of left this one hanging a couple weeks ago and haven't tested it.  If you have your blowing up example still handy, we could run a test with my changes, including `normalVelocity` in output and make sure it gets limited to a value that makes sense.  Or we could cook up a prescribed velocity field or set the limit to a low value that we know will clip a simple test case (e.g. dome).  Maybe deliberately clipping the known velo field of the dome is the best option.  What do you think?

**Comment by trhille** [comment]
@matthewhoffman, testing on the ISMIP6 4km mesh is probably too expensive to be worthwhile. I agree with testing on the dome.

**Comment by matthewhoffman** [comment]
## Testing
Ran`dome/2000m/fo_decomposition_test` with `config_unrealistic_velocity = 9.52380952e-7` (30 m/yr; dome has max speed of about 70 m/yr).

decomp test comparison on 1 and 4 procs passed.

This image shows `normalVelocity` on left and `surfaceSpeed` on right.  Results look correct.  I'm not sure if this needs to be interrogated more carefully than this.

image

Note: paraview_vtk_converter seems unable to process edge fields with a vertical dimension, so I plotted normalVelocity in ipython:
```
import netCDF4
f=netCDF4.Dataset('output.nc','r')
x=f.variables['xEdge'][:]
y=f.variables['yEdge'][:]
nv=f.variables['normalVelocity']
plt.scatter(x,y, s=9, c=np.absolute(nv[0,:,0])); plt.colorbar()
```

**Comment by trhille** [comment]
@matthewhoffman, in your plot of `normalVelocity`, it looks like there are alternating sectors of yellow and green velocity. Is that true or a trick of my poor old eyes? If it's real, is it expected?

> Note: paraview_vtk_converter seems unable to process edge fields with a vertical dimension, so I plotted normalVelocity in ipython:

This is functionality we could probably easily add to plot_maps.py

**Comment by matthewhoffman** [comment]
The alternating pattern is real and expected.  Because normalVelocity is a single velocity (normal) component, its value is strongly controlled by the edge orientation, which has this sector-based appearance on a regular hex mesh.  So I sort of high pass filter with my eyes - optimally oriented edges will have the max expected value, while there will be plenty of edges that have much lower values.  I think it's clear from the colorbar that the same capping as surfaceSpeed is happening.  What's not easy to evaluate is if the complicated logic I wrote that should lead to some sort of interpolated normalVelocity values between it's neighboring cell values is dong exactly what was intended.  It's certainly not doing anything obviously wrong, but it's hard to evaluate if it's exactly right.

**Comment by matthewhoffman** [comment]
Here is a plot of the ratio of normalVelocity to the average of the velocity of the two neighboring cells.  It never exceeds 1 which is what should happen.  We expect it to often be less than 1 because of the edge orientation issue I mentioned in the previous comment.  I can't think of a way to easily dig deeper than this, so I'm happy to consider this sufficient testing if you are.

image

**Comment by trhille** [comment]
Okay, then I'm happy with this PR!

> It's certainly not doing anything obviously wrong, but it's hard to evaluate if it's exactly right.

If you want to test this further, we could write out `scaling_factor` for a few time steps. I don't think it matters much to get it _extactly_ right (although of course that's preferable), since this is an ad hoc squashing of an instability, we will always set it to some very high number, and hopefully it does not get applied more than once in a long while.

**Review by matthewhoffman — APPROVED** [review]

**Pull request merged**
